env: standard
runtime: nodejs10
service: default
handlers:
  - url: /static
    static_dir: client/build/static

  - url: /assets
    static_dir: client/build/assets

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$

  - url: /(.*\.(html))$
    static_files: client/build/index.html
    upload: client/build/index.html
